// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKdtqMXTHyOoSB6WaqimZA-5jAQTmlTU',
    appId: '1:964296765272:web:da6352654e4609df2eff2d',
    messagingSenderId: '964296765272',
    projectId: 'chikusaiapp',
    authDomain: 'chikusaiapp.firebaseapp.com',
    storageBucket: 'chikusaiapp.firebasestorage.app',
    measurementId: 'G-8MS353EVB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQpAOck-lMscxmK7KLqci6AhrBeezgpA',
    appId: '1:964296765272:android:68a90ce16195ad822eff2d',
    messagingSenderId: '964296765272',
    projectId: 'chikusaiapp',
    storageBucket: 'chikusaiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7j0Gawl5DSGRDXwW8JjCGDavkacbqmc4',
    appId: '1:964296765272:ios:97212a0c5d6ce1e02eff2d',
    messagingSenderId: '964296765272',
    projectId: 'chikusaiapp',
    storageBucket: 'chikusaiapp.firebasestorage.app',
    iosBundleId: 'com.example.chikusaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7j0Gawl5DSGRDXwW8JjCGDavkacbqmc4',
    appId: '1:964296765272:ios:97212a0c5d6ce1e02eff2d',
    messagingSenderId: '964296765272',
    projectId: 'chikusaiapp',
    storageBucket: 'chikusaiapp.firebasestorage.app',
    iosBundleId: 'com.example.chikusaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvKdtqMXTHyOoSB6WaqimZA-5jAQTmlTU',
    appId: '1:964296765272:web:7f8b301088192bfb2eff2d',
    messagingSenderId: '964296765272',
    projectId: 'chikusaiapp',
    authDomain: 'chikusaiapp.firebaseapp.com',
    storageBucket: 'chikusaiapp.firebasestorage.app',
    measurementId: 'G-G3BD1C19K0',
  );
}
